### ISSUE TITLE
Colored gaussians

### ISSUE THREAD

**Issue by rafaelpap** [radi0sus/orca_ir#1]
Dear Sir,
in order to produce a plot similar to the last one with colored gaussians, it should be enough to make the following changes?

```
ax.set_prop_cycle('color', plt.cm.tab10.colors)
for index, freq in enumerate(freqlist):
    #single gauss function line plot
    if show_single_gauss:
        ax.plot(plt_range_x,gauss(intenslist[index], plt_range_x, freq, w),alpha=0.5) 
    #single gauss function filled plot
    if show_single_gauss_area:
        ax.fill_between(plt_range_x,gauss(intenslist[index], plt_range_x, freq, w),alpha=0.5)

```
Thanks in advance,
Rafael RP

**Comment by radi0sus** [comment]
Dear Rafael,

Simply remove `color='grey'`. 

For specific color cycles `ax.set_prop_cycle` can be used as instruction; e.g. `ax.set_prop_cycle('color', plt.cm.tab10.colors)` (your suggestion) or `ax.set_prop_cycle('color',plt.cm.plasma(np.linspace(0,1,len(freqlist))))` for example.
In all cases `color='grey'` should be removed and `show_single_gauss` and `show_single_gauss_area` should be `True` (`show_single_gauss = True` and `show_single_gauss_area = True`). 

Best regards,
Sebastian

**Comment by rafaelpap** [comment]
Thanks a lot.
